# Generated by Django 5.0.7 on 2024-08-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='all', max_length=15),
        ),
    ]
