# Generated by Django 5.0.7 on 2024-08-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_grade_assignment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('MATHEMATICS', 'MATHEMATICS'), ('ENGLISH', 'ENGLISH'), ('KISWAHILI', 'KISWAHILI'), ('CHEMISTRY', 'CHEMISTRY'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('BUSINESS STUDIES', 'BUSINESS STUDIES'), ('COMPUTER STUDIES', 'COMPUTER STUDIES'), ('AGRICULTURE', 'AGRICULTURE'), ('HOME SCIENCE', 'HOME SCIENCE'), ('HISTORY', 'HISTORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CRE', 'CRE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='AUGUST HOLIDAY ASSIGNMENT', max_length=200),
        ),
    ]
